### ISSUE TITLE
Improved Crafting Log does not switch to correct job

### ISSUE THREAD

**Issue by drejjmit** [Caraxi/SimpleTweaksPlugin#413]
Improved Crafting Log does not switch to correct job. 
It switches from combat to crafting job, but Switch Job on a Armorcraft synthesis swaps to Carpenter(?)

Simple Tweaks v1.8.0.0

**Comment by Caraxi** [comment]
I'll investigate. ty

**Comment by Caraxi** [comment]
Fixed with updated Client Structs

**Comment by drejjmit** [comment]
Still doesn't seem to work with v1.8.0.1
Tried reinstalling Simple Tweaks and restarted the client

**Comment by Caraxi** [comment]
It is known, its because Client Structs wasn't updated before Simple Tweaks, sorry not much I can do about update orders
will be fixed eventually its out of my control now
