### ISSUE TITLE
Job gauges showing when queueing after most recent update

### ISSUE THREAD

**Issue by blvcklotus** [Caraxi/SimpleTweaksPlugin#598]
This is occurring while I have all checkboxes for the Hide Job Gauges option enabled and am just standing around in the overworld. The job gauge will appear after queueing up for a duty from the Duty Finder

**Comment by Caraxi** [comment]
Fixed with fd47c5772d1b7ce68a10b1dadf32d2a6917beea2

**Comment by BarrowRoll** [comment]
This is still occurring for me on version 1.9.7.3. I have tried resetting plugin data, deleting and reinstalling the plugin, and disabling all other plugins, still occurs.
